import type { TenantTxClient } from "@/lib/db/tenantContext";

export type EvidenceCreateInput = {
  /** Generated by the caller so the storage key can be built in one write. */
  id: string;
  jobId: string;
  uploadedByUserId: string;
  storageKey: string;
  mimeType: string;
  caption?: string | null;
};

export type EvidenceConfirmInput = {
  byteSize?: number | null;
  width?: number | null;
  height?: number | null;
  clientSha256?: string | null;
  capturedAt?: Date | null;
};

/**
 * All tenant-scoped Prisma access for `evidence` must go through this
 * module -- never `prisma.evidence.*` directly elsewhere (see the
 * no-restricted-syntax rule in eslint.config.mjs). Every function
 * requires an already org-scoped transaction client (from
 * withAuthenticatedOrgContext).
 *
 * Two invariants are enforced here rather than left to callers:
 *   - reads never return tombstoned rows (deletedAt is not null) or rows
 *     whose bytes were never confirmed (uploadStatus = pending)
 *   - every lookup is scoped by organizationId *and* jobId, so a valid
 *     evidence id from another job can't be addressed through this one
 */
export const evidenceRepository = {
  /** Visible evidence for a job: confirmed uploads that aren't deleted. */
  async listForJob(tx: TenantTxClient, orgId: string, jobId: string) {
    return tx.evidence.findMany({
      where: {
        organizationId: orgId,
        jobId,
        uploadStatus: "ready",
        deletedAt: null,
      },
      orderBy: { createdAt: "asc" },
    });
  },

  async countForJob(tx: TenantTxClient, orgId: string, jobId: string) {
    return tx.evidence.count({
      where: {
        organizationId: orgId,
        jobId,
        uploadStatus: "ready",
        deletedAt: null,
      },
    });
  },

  /**
   * Includes `pending` rows on purpose -- the confirm and delete flows
   * both need to address a row that isn't `ready` yet. Still excludes
   * tombstones.
   */
  async getById(
    tx: TenantTxClient,
    orgId: string,
    jobId: string,
    evidenceId: string,
  ) {
    return tx.evidence.findFirst({
      where: {
        id: evidenceId,
        organizationId: orgId,
        jobId,
        deletedAt: null,
      },
    });
  },

  async create(tx: TenantTxClient, orgId: string, data: EvidenceCreateInput) {
    const { id, jobId, uploadedByUserId, storageKey, mimeType, caption } = data;
    return tx.evidence.create({
      data: {
        id,
        organizationId: orgId,
        jobId,
        uploadedByUserId,
        storageKey,
        mimeType,
        caption: caption ?? null,
      },
    });
  },

  /** Moves a row from `pending` to `ready` once the bytes are actually up. */
  async markReady(
    tx: TenantTxClient,
    orgId: string,
    jobId: string,
    evidenceId: string,
    data: EvidenceConfirmInput,
  ) {
    return tx.evidence.update({
      where: { id: evidenceId, organizationId: orgId, jobId },
      data: { ...data, uploadStatus: "ready" },
    });
  },

  /**
   * Tombstone, not a row delete: a later AI assessment that cited this
   * evidence must be able to report that it was deleted rather than
   * dangle against a missing id. The Storage object itself is hard-deleted
   * separately by the caller.
   */
  async softDelete(
    tx: TenantTxClient,
    orgId: string,
    jobId: string,
    evidenceId: string,
    deletedByUserId: string,
  ) {
    return tx.evidence.update({
      where: { id: evidenceId, organizationId: orgId, jobId },
      data: { deletedAt: new Date(), deletedByUserId },
    });
  },
};
